### ISSUE TITLE
No matching version found for regenerate-unicode-properties@^8.0.2

### ISSUE THREAD

**Issue by anaerobic** [mathiasbynens/regenerate-unicode-properties#2]
Getting this error on `npm i`:
```
...
npm ERR! code ETARGET
npm ERR! notarget No matching version found for regenerate-unicode-properties@^8.0.2
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'regexpu-core'
...
```

**Comment by mathiasbynens** [comment]
Hmm, the package does exist according to npm: https://www.npmjs.com/package/regenerate-unicode-properties/v/8.0.2

**Comment by dhivahar19** [comment]
Getting this error.............. when doing **npm install**

`npm ERR! code ETARGET
npm ERR! notarget No matching version found for regenerate-unicode-properties@^8.2.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'regexpu-core'`
